$ErrorActionPreference = 'Stop'

# Builds the Angular "Flight Deck" console and mirrors its production output into the API's
# wwwroot, so `dotnet run --project src/HighPerf.Api` alone can serve both the engine and the
# console from a single origin. wwwroot is a build artifact (see .gitignore) - always
# regenerated by this script, never committed.

$repoRoot = Join-Path $PSScriptRoot '..'
$webDir = Join-Path $repoRoot 'web'
$distBrowserDir = Join-Path $webDir 'dist\highperf-web\browser'
$wwwrootDir = Join-Path $repoRoot 'src\HighPerf.Api\wwwroot'

if (-not (Test-Path (Join-Path $webDir 'node_modules'))) {
    Write-Host 'web/node_modules missing - running npm ci...'
    Push-Location $webDir
    try {
        npm ci --silent
        if ($LASTEXITCODE -ne 0) { throw "npm ci failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }
}

Write-Host 'Building the Angular production bundle (npm run build)...'
Push-Location $webDir
try {
    npm run build
    if ($LASTEXITCODE -ne 0) { throw "npm run build failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

# Angular 22's application builder emits the browser bundle to dist/highperf-web/browser
# (not dist/highperf-web directly) - verify it actually produced an entry point before we
# wipe the previous wwwroot, so a broken build never leaves the API with no client at all.
$indexHtml = Join-Path $distBrowserDir 'index.html'
if (-not (Test-Path $indexHtml)) {
    throw "Build output not found at $indexHtml - expected the Angular application builder to emit dist/highperf-web/browser/index.html"
}

if (Test-Path $wwwrootDir) {
    Remove-Item $wwwrootDir -Recurse -Force
}
New-Item -ItemType Directory -Force $wwwrootDir | Out-Null
Copy-Item (Join-Path $distBrowserDir '*') $wwwrootDir -Recurse -Force

$files = Get-ChildItem $wwwrootDir -Recurse -File
$totalBytes = ($files | Measure-Object -Property Length -Sum).Sum
$totalKb = [Math]::Round($totalBytes / 1KB, 1)
Write-Host "Published $($files.Count) files ($totalKb KB) to $wwwrootDir"
